language: node_js

node_js:
  - 12

services:
  - docker

before_script:
  - docker-compose up -d

script:
  - echo "----- Running backend tests -----"
  - docker-compose -p api-tests run --rm api npm run test:unit
  # - echo "----- Running frontend tests -----"
  # - docker-compose -p client-tests run --rm client npm run test:unit
after_success:
  - docker image build -t whoisju1/news-grubber-api -f ./api
  - docker image build -t whoisju1/news-grubber-client -f ./client
  - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_USERNAME" --password-stdin
  - docker image push whoisju1/news-grubber-api
  - docker iamge push whoisju1/news-grubber-client

# deploy:
#   provider: heroku
#   api_key:
#     secure: KEY
#   app: news-grubber
#   on:
#     repo: News-Grubber