language: node_js

node_js:
  - 12

services:
  - docker

before_script:
  - echo "----- Running backend tests -----"
  - docker-compose -p api-tests run --rm api npm run test:unit
  - echo "----- Running frontend tests -----"
  - docker-compose -p client-tests run --rm client npm run test:unit

deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: news-grubber
  on:
    repo: News-Grubber