language: node_js

node_js:
  - 12

services:
  - docker

before_script:
  - chmod 777 ./run_tests.sh
  - ./run_tests.sh

deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: news-grubber
  on:
    repo: News-Grubber