# version: '3'
# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#     - "5000:5000"
#     volumes:
#       - ./:/api
#       - /node_modules
#     env_file:
#       - ./.env