version: '3.7'
networks:
  unit-tests-network:
    driver: bridge

services:
  test-db-mongo:
    image: mongo:4.4.4
    restart: always
    networks:
      - unit-tests-network
  test-db-redis:
    image: redis:6.2.1
    expose:
      - '6379'
    networks:
      - unit-tests-network
    restart: always
  api_unit_tests:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - test-db-mongo
      - test-db-redis
    volumes:
      - ./api/node_modules
      - ./api:/api
    environment:
      NODE_ENV: test
      MONGODB_URI: mongodb://test-db-mongo:27017/news-grubber-test
      PORT: 5001
      REDIS_HOST: test-db-redis
      BCRYPT_SECRET_KEY: super_secret_key
    networks:
      - unit-tests-network
  client_unit_test:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    networks:
      - unit-tests-network
    volumes:
      - ./client/node_modules
      - ./client:/client
