version: '3.7'

services:
  api:
    image: whoisju1/news-grubber-api
  client:
    image: whoisju1/news-grubber-client
    depends_on:
      - api
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  mongo:
    image: mongo:latest
