version: '3.7'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
      - ./api/node_modules
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/news-grubber-dev
      PORT: 5000
      REDIS_HOST: redis
      BCRYPT_SECRET_KEY: super_secret_key
    ports: 
      - 5000:5000
      - 9229:9229
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/node_modules
      - ./client:/client
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
    - '3000:80'
    depends_on:
      - client
      - api
