version: '3.7'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
      - ./api/node_modules
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/node_modules
      - ./client:/client
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
    - '3000:80'
    depends_on:
      - client
      - api
