version: '3.7'

services:
  api:
    deploy:
      replicas: 3
    environment:
      - "MONGODB_URI:${MONGODB_URI}"
      - "SECRETE_KEY:${SECRETE_KEY}"
      - "PORT:5000"
      - "NODE_ENV:${NODE_ENV}"
  client:
    deploy:
      replicas: 3
    ports:
      - ${PORT}:80
